# ===============================
# PUERTO DEL BACKEND
# ===============================
server.port=8080


# ===============================
# CONFIGURACIÓN POSTGRESQL
# ===============================

# URL de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pronosticup

# Usuario de PostgreSQL que creaste en pgAdmin
spring.datasource.username=pronosticup

# Contraseña del usuario
spring.datasource.password=pronosticup

# Driver de PostgreSQL (necesario para conectar)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion para comprobar que si la base de datos conecta bien mediante edbug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# ===============================
# CONFIGURACIÓN JPA / HIBERNATE
# ===============================

# Crea las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Dialecto de PostgreSQL (evita el error que te salía)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# CONFIGURACIÓN MONGODB
# ===============================

# URL de conexión a MongoDB
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/pronosticup



