# ===============================
# PUERTO DEL BACKEND
# ===============================
server.port=8080


# ===============================
# CONFIGURACIÓN POSTGRESQL
# ===============================

# URL de conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/pronosticup

# Usuario de PostgreSQL que creaste en pgAdmin
spring.datasource.username=pronosticup

# Contraseña del usuario
spring.datasource.password=pronosticup

# Driver de PostgreSQL (necesario para conectar)
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion para comprobar que si la base de datos conecta bien mediante edbug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

# ===============================
# CONFIGURACIÓN JPA / HIBERNATE
# ===============================

# Crea las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas SQL en consola
spring.jpa.show-sql=true

# Dialecto de PostgreSQL (evita el error que te salía)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# CONFIGURACIÓN MONGODB
# ===============================

# URL de conexión a MongoDB
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/pronosticup


# ===============================
# CONFIGURACIÓN PROCESOS BATCH
# ===============================
app.schedulers.tournament-sync.enabled=true
app.schedulers.score-batch.enabled=true


# ===============================
# LOGS (crea automaticamente el log en la raíz del proyecto cuando arranque la app.)
# ===============================
logging.level.root=INFO
logging.level.SCORE_BATCH=INFO



# ===============================
# API EXTERNA (Configuración de la API externa)
# ===============================
football-data.base-url=http://api.football-data.org
football-data.token=769ea93e56744920996695158e064f2c
football-data.competition.world-cup=2000
football-data.competition.euro-cup=2018


# ===============================
# GMAIL
# ===============================
# BREVO SMTP
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OPCIONAL (recomendado)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${APP_MAIL_FROM}

app.security.pronostic-encryption-key=${PRONOSTIC_ENCRYPTION_KEY}

