server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.mail.host=${SPRING_MAIL_HOST:smtp-relay.brevo.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${APP_MAIL_FROM}
app.security.pronostic-encryption-key=${PRONOSTIC_ENCRYPTION_KEY}

football-data.token=${FOOTBALL_DATA_TOKEN}
football-data.base-url=${FOOTBALL_DATA_BASE_URL:http://api.football-data.org}
football-data.competition.world-cup=${FOOTBALL_WORLD_CUP_CODE:2000}
football-data.competition.euro-cup=${FOOTBALL_EURO_CUP_CODE:2018}

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.forward-headers-strategy=framework