spring.application.name=pronosticup-backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.schedulers.tournament-sync.enabled=${APP_SCHEDULERS_TOURNAMENT_SYNC_ENABLED:false}
app.schedulers.score-batch.enabled=${APP_SCHEDULERS_SCORE_BATCH_ENABLED:false}
app.scores.use-local-snapshots=false

logging.level.root=INFO
logging.level.SCORE_BATCH=INFO

football-data.base-url=http://api.football-data.org
football-data.competition.world-cup=2000
football-data.competition.euro-cup=2018

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000